

[mosip_auth]
timestamp_format = "%Y-%m-%dT%H:%M:%S"
ida_auth_version = '1.0'
ida_auth_request_id = 'mosip.identity.auth'
ida_auth_env = 'Staging'
authorization_header_constant = 'Authorization'
partner_apikey = '449869'
partner_misp_lk = 'bmgDCMGV8zSnpBV5b0Qe1L3GtY9RXPSBkUcVfONP9AkOsKYVLy'
partner_id = 'openg2p'

[mosip_auth.server]
ida_auth_domain_uri = 'https://api-internal.iiitb.mosip.net'
ida_auth_url = 'https://api-internal.iiitb.mosip.net/idauthentication/v1/auth'


[crypto.encrypt]
algorithm = '@none'
symmetric_key_size = 256
symmetric_nonce_size = 128
symmetric_gcm_tag_size = 128
# below certificate is used to encrypt the Auth Request.
encrypt_cert_path = '/opt/taheer-mos/mosip/openg2p/test-certs/ida.partner.cert'

[crypto.signature]
algorithm = 'RS256'
sign_p12_file_path = '/opt/taheer-mos/mosip/openg2p/test-certs/openg2p.p12'
sign_p12_file_password = '123456'

[logging]
log_file_path = '/opt/taheer-mos/mosip/openg2p/test-certs/authenticator.log'