[root]
context_path = '/'
pid_grep_name = 'gunicorn'
default_lang_code = "eng"
output_stored_files_path = "stored_files"


[mosip_auth_server]
# ida_auth_domain_uri = 
# ida_auth_url = 

ida_auth_domain_uri = "https://api-internal.iiitb.mosip.net"
ida_auth_url = "https://api-internal.iiitb.mosip.net/idauthentication/v1/auth"

[logging]
log_file_name = "mosip_token_seeder.log"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[db]
location = 'sqlite+pysqlcipher://:<password>@/auth_token_seeder.dbsqlite'
username = ''
password = ''
random_password_length = 16
generate_db_always = true
generate_password_always = true
print_password_on_startup = true


[gunicorn]
worker_id = 0
# the following are set using env variables
# workers
# max_requests
# timeout
# keep_alive

[docker]
pod_name = 'token-seeder-0'
pod_id = 0
replicas = 1