[root]
context_path = '/'
pid_grep_name = 'gunicorn'
default_lang_code = "eng"
output_stored_files_path = "stored_files"

[logging]
log_file_name = "mosip_token_seeder.log"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[db]
location = 'sqlite+pysqlcipher://:<password>@/auth_token_seeder.db'
username = ''
password = ''
generate_db_always = true
generate_password_always = true


[gunicorn]
worker_id = 0
# the following are set using env variables
# workers
# max_requests
# timeout
# keep_alive

[docker]
pod_name = 'token-seeder-0'
pod_id = 0
replicas = 1