name: MOSIP Token Seeder Docker Build upon push

on:
  push:
    paths:
      - mosip_token_seeder/**

jobs:
  token-seeder-build:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.dev_namespace_docker_hub }}
      SERVICE_NAME: mosip-token-seeder
      SERVICE_LOCATION: mosip_token_seeder
    steps:
      - uses: actions/checkout@v2

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
      - name: Docker build & push
        run: |
          IMAGE_ID=$NAMESPACE/$SERVICE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          if [[ $BRANCH_NAME == master || $BRANCH_NAME == main ]]; then
            VERSION=latest
          else
            VERSION=$BRANCH_NAME
          fi
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          cd "./${{env.SERVICE_LOCATION}}"
          docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION
      - name: Docker login
        run: |
          echo "${{ secrets.release_docker_hub }}" | docker login -u ${{ secrets.actor_docker_hub }} --password-stdin
      - name: Docker push
        run: |
          docker push $IMAGE_ID:$VERSION